/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ColumnReference
 */
public class ColumnReferenceTest {
    private final ColumnReference model = new ColumnReference();

    /**
     * Model tests for ColumnReference
     */
    @Test
    public void testColumnReference() {
        // TODO: test ColumnReference
    }

    /**
     * Test the property 'columnID'
     */
    @Test
    public void columnIDTest() {
        // TODO: test columnID
    }

    /**
     * Test the property 'nodeID'
     */
    @Test
    public void nodeIDTest() {
        // TODO: test nodeID
    }

}
