/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EnvironmentHealth;
import com.konfigthis.client.model.TagColor;
import com.konfigthis.client.model.UserSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EnvironmentsResponseDataInner
 */
public class EnvironmentsResponseDataInnerTest {
    private final EnvironmentsResponseDataInner model = new EnvironmentsResponseDataInner();

    /**
     * Model tests for EnvironmentsResponseDataInner
     */
    @Test
    public void testEnvironmentsResponseDataInner() {
        // TODO: test EnvironmentsResponseDataInner
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'connectionAccount'
     */
    @Test
    public void connectionAccountTest() {
        // TODO: test connectionAccount
    }

    /**
     * Test the property 'defaultStorageMapping'
     */
    @Test
    public void defaultStorageMappingTest() {
        // TODO: test defaultStorageMapping
    }

    /**
     * Test the property 'oauthEnabled'
     */
    @Test
    public void oauthEnabledTest() {
        // TODO: test oauthEnabled
    }

    /**
     * Test the property 'runTimeParameters'
     */
    @Test
    public void runTimeParametersTest() {
        // TODO: test runTimeParameters
    }

    /**
     * Test the property 'tagColors'
     */
    @Test
    public void tagColorsTest() {
        // TODO: test tagColors
    }

}
