/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ColumnReference;
import com.konfigthis.client.model.HashAlgorithm;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HashMetadata
 */
public class HashMetadataTest {
    private final HashMetadata model = new HashMetadata();

    /**
     * Model tests for HashMetadata
     */
    @Test
    public void testHashMetadata() {
        // TODO: test HashMetadata
    }

    /**
     * Test the property 'hashAlgorithm'
     */
    @Test
    public void hashAlgorithmTest() {
        // TODO: test hashAlgorithm
    }

    /**
     * Test the property 'hashType'
     */
    @Test
    public void hashTypeTest() {
        // TODO: test hashType
    }

    /**
     * Test the property 'hubHashes'
     */
    @Test
    public void hubHashesTest() {
        // TODO: test hubHashes
    }

}
