/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HashAlgorithm
 */
public class HashAlgorithmTest {
    /**
     * Model tests for HashAlgorithm
     */
    @Test
    public void testHashAlgorithm() {
        // TODO: test HashAlgorithm
    }

}
