/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsGetStatusUpdatesResponse
 */
public class JobsGetStatusUpdatesResponseTest {
    private final JobsGetStatusUpdatesResponse model = new JobsGetStatusUpdatesResponse();

    /**
     * Model tests for JobsGetStatusUpdatesResponse
     */
    @Test
    public void testJobsGetStatusUpdatesResponse() {
        // TODO: test JobsGetStatusUpdatesResponse
    }

    /**
     * Test the property 'runStatus'
     */
    @Test
    public void runStatusTest() {
        // TODO: test runStatus
    }

    /**
     * Test the property 'runType'
     */
    @Test
    public void runTypeTest() {
        // TODO: test runType
    }

    /**
     * Test the property 'runLink'
     */
    @Test
    public void runLinkTest() {
        // TODO: test runLink
    }

}
