/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsInitiateRunRequestRunDetails
 */
public class JobsInitiateRunRequestRunDetailsTest {
    private final JobsInitiateRunRequestRunDetails model = new JobsInitiateRunRequestRunDetails();

    /**
     * Model tests for JobsInitiateRunRequestRunDetails
     */
    @Test
    public void testJobsInitiateRunRequestRunDetails() {
        // TODO: test JobsInitiateRunRequestRunDetails
    }

    /**
     * Test the property 'environmentID'
     */
    @Test
    public void environmentIDTest() {
        // TODO: test environmentID
    }

    /**
     * Test the property 'includeNodesSelector'
     */
    @Test
    public void includeNodesSelectorTest() {
        // TODO: test includeNodesSelector
    }

    /**
     * Test the property 'excludeNodesSelector'
     */
    @Test
    public void excludeNodesSelectorTest() {
        // TODO: test excludeNodesSelector
    }

    /**
     * Test the property 'jobID'
     */
    @Test
    public void jobIDTest() {
        // TODO: test jobID
    }

    /**
     * Test the property 'parallelism'
     */
    @Test
    public void parallelismTest() {
        // TODO: test parallelism
    }

    /**
     * Test the property 'forceIgnoreWorkspaceStatus'
     */
    @Test
    public void forceIgnoreWorkspaceStatusTest() {
        // TODO: test forceIgnoreWorkspaceStatus
    }

}
