/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsTriggerRerunResponse
 */
public class JobsTriggerRerunResponseTest {
    private final JobsTriggerRerunResponse model = new JobsTriggerRerunResponse();

    /**
     * Model tests for JobsTriggerRerunResponse
     */
    @Test
    public void testJobsTriggerRerunResponse() {
        // TODO: test JobsTriggerRerunResponse
    }

    /**
     * Test the property 'runCounter'
     */
    @Test
    public void runCounterTest() {
        // TODO: test runCounter
    }

}
