/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JobsTriggerRerunRequestRunDetails;
import com.konfigthis.client.model.JobsTriggerRerunRequestUserCredentials;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsTriggerRerunRequest
 */
public class JobsTriggerRerunRequestTest {
    private final JobsTriggerRerunRequest model = new JobsTriggerRerunRequest();

    /**
     * Model tests for JobsTriggerRerunRequest
     */
    @Test
    public void testJobsTriggerRerunRequest() {
        // TODO: test JobsTriggerRerunRequest
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'runDetails'
     */
    @Test
    public void runDetailsTest() {
        // TODO: test runDetails
    }

    /**
     * Test the property 'userCredentials'
     */
    @Test
    public void userCredentialsTest() {
        // TODO: test userCredentials
    }

}
