/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsCancelJobRunRequest
 */
public class JobsCancelJobRunRequestTest {
    private final JobsCancelJobRunRequest model = new JobsCancelJobRunRequest();

    /**
     * Model tests for JobsCancelJobRunRequest
     */
    @Test
    public void testJobsCancelJobRunRequest() {
        // TODO: test JobsCancelJobRunRequest
    }

    /**
     * Test the property 'runID'
     */
    @Test
    public void runIDTest() {
        // TODO: test runID
    }

    /**
     * Test the property 'orgID'
     */
    @Test
    public void orgIDTest() {
        // TODO: test orgID
    }

    /**
     * Test the property 'environmentID'
     */
    @Test
    public void environmentIDTest() {
        // TODO: test environmentID
    }

}
