/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TestRunOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NodeTest
 */
public class NodeTestTest {
    private final NodeTest model = new NodeTest();

    /**
     * Model tests for NodeTest
     */
    @Test
    public void testNodeTest() {
        // TODO: test NodeTest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'continueOnFailure'
     */
    @Test
    public void continueOnFailureTest() {
        // TODO: test continueOnFailure
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'runOrder'
     */
    @Test
    public void runOrderTest() {
        // TODO: test runOrder
    }

    /**
     * Test the property 'templateString'
     */
    @Test
    public void templateStringTest() {
        // TODO: test templateString
    }

}
