/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Error;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for QueryResult
 */
public class QueryResultTest {
    private final QueryResult model = new QueryResult();

    /**
     * Model tests for QueryResult
     */
    @Test
    public void testQueryResult() {
        // TODO: test QueryResult
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'isRunning'
     */
    @Test
    public void isRunningTest() {
        // TODO: test isRunning
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'queryID'
     */
    @Test
    public void queryIDTest() {
        // TODO: test queryID
    }

    /**
     * Test the property 'rowsDeleted'
     */
    @Test
    public void rowsDeletedTest() {
        // TODO: test rowsDeleted
    }

    /**
     * Test the property 'rowsInserted'
     */
    @Test
    public void rowsInsertedTest() {
        // TODO: test rowsInserted
    }

    /**
     * Test the property 'rowsUpdated'
     */
    @Test
    public void rowsUpdatedTest() {
        // TODO: test rowsUpdated
    }

    /**
     * Test the property 'sql'
     */
    @Test
    public void sqlTest() {
        // TODO: test sql
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'warehouse'
     */
    @Test
    public void warehouseTest() {
        // TODO: test warehouse
    }

}
