/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.RegistryPackageReleaseResultCreatedAt;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RegistryPackageReleaseResult
 */
public class RegistryPackageReleaseResultTest {
    private final RegistryPackageReleaseResult model = new RegistryPackageReleaseResult();

    /**
     * Model tests for RegistryPackageReleaseResult
     */
    @Test
    public void testRegistryPackageReleaseResult() {
        // TODO: test RegistryPackageReleaseResult
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'changeLog'
     */
    @Test
    public void changeLogTest() {
        // TODO: test changeLog
    }

    /**
     * Test the property 'packageID'
     */
    @Test
    public void packageIDTest() {
        // TODO: test packageID
    }

    /**
     * Test the property 'releaseID'
     */
    @Test
    public void releaseIDTest() {
        // TODO: test releaseID
    }

    /**
     * Test the property 'storagePath'
     */
    @Test
    public void storagePathTest() {
        // TODO: test storagePath
    }

}
