/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DRRunDetails;
import com.konfigthis.client.model.RunStatus;
import com.konfigthis.client.model.RunType;
import com.konfigthis.client.model.SnowflakeUserCredentials;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RunInfo
 */
public class RunInfoTest {
    private final RunInfo model = new RunInfo();

    /**
     * Model tests for RunInfo
     */
    @Test
    public void testRunInfo() {
        // TODO: test RunInfo
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'reRunID'
     */
    @Test
    public void reRunIDTest() {
        // TODO: test reRunID
    }

    /**
     * Test the property 'runDetails'
     */
    @Test
    public void runDetailsTest() {
        // TODO: test runDetails
    }

    /**
     * Test the property 'runEndTime'
     */
    @Test
    public void runEndTimeTest() {
        // TODO: test runEndTime
    }

    /**
     * Test the property 'runHistory'
     */
    @Test
    public void runHistoryTest() {
        // TODO: test runHistory
    }

    /**
     * Test the property 'runStartTime'
     */
    @Test
    public void runStartTimeTest() {
        // TODO: test runStartTime
    }

    /**
     * Test the property 'runStatus'
     */
    @Test
    public void runStatusTest() {
        // TODO: test runStatus
    }

    /**
     * Test the property 'runTimeParameters'
     */
    @Test
    public void runTimeParametersTest() {
        // TODO: test runTimeParameters
    }

    /**
     * Test the property 'runType'
     */
    @Test
    public void runTypeTest() {
        // TODO: test runType
    }

    /**
     * Test the property 'userCredentials'
     */
    @Test
    public void userCredentialsTest() {
        // TODO: test userCredentials
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

}
