/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ColumnReference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SourceColumnReferenceV1
 */
public class SourceColumnReferenceV1Test {
    private final SourceColumnReferenceV1 model = new SourceColumnReferenceV1();

    /**
     * Model tests for SourceColumnReferenceV1
     */
    @Test
    public void testSourceColumnReferenceV1() {
        // TODO: test SourceColumnReferenceV1
    }

    /**
     * Test the property 'columnReferences'
     */
    @Test
    public void columnReferencesTest() {
        // TODO: test columnReferences
    }

    /**
     * Test the property 'transform'
     */
    @Test
    public void transformTest() {
        // TODO: test transform
    }

}
