/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SourceColumnMetadataJoin
 */
public class SourceColumnMetadataJoinTest {
    private final SourceColumnMetadataJoin model = new SourceColumnMetadataJoin();

    /**
     * Model tests for SourceColumnMetadataJoin
     */
    @Test
    public void testSourceColumnMetadataJoin() {
        // TODO: test SourceColumnMetadataJoin
    }

    /**
     * Test the property 'joinCondition'
     */
    @Test
    public void joinConditionTest() {
        // TODO: test joinCondition
    }

}
