/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ColumnMetadata;
import com.konfigthis.client.model.SourceColumnMetadataJoin;
import com.konfigthis.client.model.SourceMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SourceColumnMetadata
 */
public class SourceColumnMetadataTest {
    private final SourceColumnMetadata model = new SourceColumnMetadata();

    /**
     * Model tests for SourceColumnMetadata
     */
    @Test
    public void testSourceColumnMetadata() {
        // TODO: test SourceColumnMetadata
    }

    /**
     * Test the property 'columns'
     */
    @Test
    public void columnsTest() {
        // TODO: test columns
    }

    /**
     * Test the property 'join'
     */
    @Test
    public void joinTest() {
        // TODO: test join
    }

    /**
     * Test the property 'sourceMapping'
     */
    @Test
    public void sourceMappingTest() {
        // TODO: test sourceMapping
    }

}
