/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ColumnMetadata;
import com.konfigthis.client.model.NodeTest;
import com.konfigthis.client.model.SourceMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SQLNodeMetadata
 */
public class SQLNodeMetadataTest {
    private final SQLNodeMetadata model = new SQLNodeMetadata();

    /**
     * Model tests for SQLNodeMetadata
     */
    @Test
    public void testSQLNodeMetadata() {
        // TODO: test SQLNodeMetadata
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'appliedNodeTests'
     */
    @Test
    public void appliedNodeTestsTest() {
        // TODO: test appliedNodeTests
    }

    /**
     * Test the property 'columns'
     */
    @Test
    public void columnsTest() {
        // TODO: test columns
    }

    /**
     * Test the property 'cteString'
     */
    @Test
    public void cteStringTest() {
        // TODO: test cteString
    }

    /**
     * Test the property 'destinationName'
     */
    @Test
    public void destinationNameTest() {
        // TODO: test destinationName
    }

    /**
     * Test the property 'enabledColumnTestIDs'
     */
    @Test
    public void enabledColumnTestIDsTest() {
        // TODO: test enabledColumnTestIDs
    }

    /**
     * Test the property 'mapping'
     */
    @Test
    public void mappingTest() {
        // TODO: test mapping
    }

    /**
     * Test the property 'materializationOption'
     */
    @Test
    public void materializationOptionTest() {
        // TODO: test materializationOption
    }

    /**
     * Test the property 'sourceMapping'
     */
    @Test
    public void sourceMappingTest() {
        // TODO: test sourceMapping
    }

}
