/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ColumnReference;
import com.konfigthis.client.model.HashAlgorithm;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * HashMetadata
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class HashMetadata {
  public static final String SERIALIZED_NAME_HASH_ALGORITHM = "hashAlgorithm";
  @SerializedName(SERIALIZED_NAME_HASH_ALGORITHM)
  private HashAlgorithm hashAlgorithm;

  /**
   * Gets or Sets hashType
   */
  @JsonAdapter(HashTypeEnum.Adapter.class)
 public enum HashTypeEnum {
    CHANGEHASH("ChangeHash"),
    
    HASH("Hash"),
    
    HUBHASH("HubHash"),
    
    LINKHASH("LinkHash"),
    
    NONE("None");

    private String value;

    HashTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static HashTypeEnum fromValue(String value) {
      for (HashTypeEnum b : HashTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<HashTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final HashTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public HashTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return HashTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_HASH_TYPE = "hashType";
  @SerializedName(SERIALIZED_NAME_HASH_TYPE)
  private HashTypeEnum hashType;

  public static final String SERIALIZED_NAME_HUB_HASHES = "hubHashes";
  @SerializedName(SERIALIZED_NAME_HUB_HASHES)
  private List<ColumnReference> hubHashes = null;

  public HashMetadata() {
  }

  public HashMetadata hashAlgorithm(HashAlgorithm hashAlgorithm) {
    
    
    
    
    this.hashAlgorithm = hashAlgorithm;
    return this;
  }

   /**
   * Get hashAlgorithm
   * @return hashAlgorithm
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public HashAlgorithm getHashAlgorithm() {
    return hashAlgorithm;
  }


  public void setHashAlgorithm(HashAlgorithm hashAlgorithm) {
    
    
    
    this.hashAlgorithm = hashAlgorithm;
  }


  public HashMetadata hashType(HashTypeEnum hashType) {
    
    
    
    
    this.hashType = hashType;
    return this;
  }

   /**
   * Get hashType
   * @return hashType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HashTypeEnum getHashType() {
    return hashType;
  }


  public void setHashType(HashTypeEnum hashType) {
    
    
    
    this.hashType = hashType;
  }


  public HashMetadata hubHashes(List<ColumnReference> hubHashes) {
    
    
    
    
    this.hubHashes = hubHashes;
    return this;
  }

  public HashMetadata addHubHashesItem(ColumnReference hubHashesItem) {
    if (this.hubHashes == null) {
      this.hubHashes = new ArrayList<>();
    }
    this.hubHashes.add(hubHashesItem);
    return this;
  }

   /**
   * Get hubHashes
   * @return hubHashes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ColumnReference> getHubHashes() {
    return hubHashes;
  }


  public void setHubHashes(List<ColumnReference> hubHashes) {
    
    
    
    this.hubHashes = hubHashes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the HashMetadata instance itself
   */
  public HashMetadata putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HashMetadata hashMetadata = (HashMetadata) o;
    return Objects.equals(this.hashAlgorithm, hashMetadata.hashAlgorithm) &&
        Objects.equals(this.hashType, hashMetadata.hashType) &&
        Objects.equals(this.hubHashes, hashMetadata.hubHashes)&&
        Objects.equals(this.additionalProperties, hashMetadata.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashAlgorithm, hashType, hubHashes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HashMetadata {\n");
    sb.append("    hashAlgorithm: ").append(toIndentedString(hashAlgorithm)).append("\n");
    sb.append("    hashType: ").append(toIndentedString(hashType)).append("\n");
    sb.append("    hubHashes: ").append(toIndentedString(hubHashes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("hashAlgorithm");
    openapiFields.add("hashType");
    openapiFields.add("hubHashes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("hashAlgorithm");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to HashMetadata
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!HashMetadata.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HashMetadata is not found in the empty JSON string", HashMetadata.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HashMetadata.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("hashType") != null && !jsonObj.get("hashType").isJsonNull()) && !jsonObj.get("hashType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashType").toString()));
      }
      if (jsonObj.get("hubHashes") != null && !jsonObj.get("hubHashes").isJsonNull()) {
        JsonArray jsonArrayhubHashes = jsonObj.getAsJsonArray("hubHashes");
        if (jsonArrayhubHashes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("hubHashes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `hubHashes` to be an array in the JSON string but got `%s`", jsonObj.get("hubHashes").toString()));
          }

          // validate the optional field `hubHashes` (array)
          for (int i = 0; i < jsonArrayhubHashes.size(); i++) {
            ColumnReference.validateJsonObject(jsonArrayhubHashes.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HashMetadata.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HashMetadata' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HashMetadata> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HashMetadata.class));

       return (TypeAdapter<T>) new TypeAdapter<HashMetadata>() {
           @Override
           public void write(JsonWriter out, HashMetadata value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public HashMetadata read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             HashMetadata instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of HashMetadata given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of HashMetadata
  * @throws IOException if the JSON string is invalid with respect to HashMetadata
  */
  public static HashMetadata fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HashMetadata.class);
  }

 /**
  * Convert an instance of HashMetadata to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

