/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Contains the runID to be re-run.
 */
@ApiModel(description = "Contains the runID to be re-run.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class JobsTriggerRerunRequestRunDetails {
  public static final String SERIALIZED_NAME_RUN_I_D = "runID";
  @SerializedName(SERIALIZED_NAME_RUN_I_D)
  private String runID;

  public static final String SERIALIZED_NAME_FORCE_IGNORE_WORKSPACE_STATUS = "forceIgnoreWorkspaceStatus";
  @SerializedName(SERIALIZED_NAME_FORCE_IGNORE_WORKSPACE_STATUS)
  private Boolean forceIgnoreWorkspaceStatus;

  public JobsTriggerRerunRequestRunDetails() {
  }

  public JobsTriggerRerunRequestRunDetails runID(String runID) {
    
    
    
    
    this.runID = runID;
    return this;
  }

   /**
   * The number of the run you want to be retried.
   * @return runID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of the run you want to be retried.")

  public String getRunID() {
    return runID;
  }


  public void setRunID(String runID) {
    
    
    
    this.runID = runID;
  }


  public JobsTriggerRerunRequestRunDetails forceIgnoreWorkspaceStatus(Boolean forceIgnoreWorkspaceStatus) {
    
    
    
    
    this.forceIgnoreWorkspaceStatus = forceIgnoreWorkspaceStatus;
    return this;
  }

   /**
   * Allows refreshing an environment even if the last deployment on that environment failed. Use with caution as this can put your environment into an even worse state.
   * @return forceIgnoreWorkspaceStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Allows refreshing an environment even if the last deployment on that environment failed. Use with caution as this can put your environment into an even worse state.")

  public Boolean getForceIgnoreWorkspaceStatus() {
    return forceIgnoreWorkspaceStatus;
  }


  public void setForceIgnoreWorkspaceStatus(Boolean forceIgnoreWorkspaceStatus) {
    
    
    
    this.forceIgnoreWorkspaceStatus = forceIgnoreWorkspaceStatus;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the JobsTriggerRerunRequestRunDetails instance itself
   */
  public JobsTriggerRerunRequestRunDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobsTriggerRerunRequestRunDetails jobsTriggerRerunRequestRunDetails = (JobsTriggerRerunRequestRunDetails) o;
    return Objects.equals(this.runID, jobsTriggerRerunRequestRunDetails.runID) &&
        Objects.equals(this.forceIgnoreWorkspaceStatus, jobsTriggerRerunRequestRunDetails.forceIgnoreWorkspaceStatus)&&
        Objects.equals(this.additionalProperties, jobsTriggerRerunRequestRunDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(runID, forceIgnoreWorkspaceStatus, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobsTriggerRerunRequestRunDetails {\n");
    sb.append("    runID: ").append(toIndentedString(runID)).append("\n");
    sb.append("    forceIgnoreWorkspaceStatus: ").append(toIndentedString(forceIgnoreWorkspaceStatus)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("runID");
    openapiFields.add("forceIgnoreWorkspaceStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("runID");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to JobsTriggerRerunRequestRunDetails
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!JobsTriggerRerunRequestRunDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobsTriggerRerunRequestRunDetails is not found in the empty JSON string", JobsTriggerRerunRequestRunDetails.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : JobsTriggerRerunRequestRunDetails.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("runID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `runID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("runID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobsTriggerRerunRequestRunDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobsTriggerRerunRequestRunDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobsTriggerRerunRequestRunDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobsTriggerRerunRequestRunDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<JobsTriggerRerunRequestRunDetails>() {
           @Override
           public void write(JsonWriter out, JobsTriggerRerunRequestRunDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public JobsTriggerRerunRequestRunDetails read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             JobsTriggerRerunRequestRunDetails instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of JobsTriggerRerunRequestRunDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of JobsTriggerRerunRequestRunDetails
  * @throws IOException if the JSON string is invalid with respect to JobsTriggerRerunRequestRunDetails
  */
  public static JobsTriggerRerunRequestRunDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobsTriggerRerunRequestRunDetails.class);
  }

 /**
  * Convert an instance of JobsTriggerRerunRequestRunDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

