/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.QueryResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The result output describing each query processed during a run.
 */
@ApiModel(description = "The result output describing each query processed during a run.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RunResult {
  public static final String SERIALIZED_NAME_IS_RUNNING = "isRunning";
  @SerializedName(SERIALIZED_NAME_IS_RUNNING)
  private Boolean isRunning;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NODE_I_D = "nodeID";
  @SerializedName(SERIALIZED_NAME_NODE_I_D)
  private String nodeID;

  public static final String SERIALIZED_NAME_QUERY_RESULTS = "queryResults";
  @SerializedName(SERIALIZED_NAME_QUERY_RESULTS)
  private List<QueryResult> queryResults = new ArrayList<>();

  public static final String SERIALIZED_NAME_RENDER_QUERY_RESULT = "renderQueryResult";
  @SerializedName(SERIALIZED_NAME_RENDER_QUERY_RESULT)
  private QueryResult renderQueryResult;

  public RunResult() {
  }

  public RunResult isRunning(Boolean isRunning) {
    
    
    
    
    this.isRunning = isRunning;
    return this;
  }

   /**
   * Get isRunning
   * @return isRunning
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsRunning() {
    return isRunning;
  }


  public void setIsRunning(Boolean isRunning) {
    
    
    
    this.isRunning = isRunning;
  }


  public RunResult name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public RunResult nodeID(String nodeID) {
    
    
    
    
    this.nodeID = nodeID;
    return this;
  }

   /**
   * Get nodeID
   * @return nodeID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNodeID() {
    return nodeID;
  }


  public void setNodeID(String nodeID) {
    
    
    
    this.nodeID = nodeID;
  }


  public RunResult queryResults(List<QueryResult> queryResults) {
    
    
    
    
    this.queryResults = queryResults;
    return this;
  }

  public RunResult addQueryResultsItem(QueryResult queryResultsItem) {
    this.queryResults.add(queryResultsItem);
    return this;
  }

   /**
   * Get queryResults
   * @return queryResults
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<QueryResult> getQueryResults() {
    return queryResults;
  }


  public void setQueryResults(List<QueryResult> queryResults) {
    
    
    
    this.queryResults = queryResults;
  }


  public RunResult renderQueryResult(QueryResult renderQueryResult) {
    
    
    
    
    this.renderQueryResult = renderQueryResult;
    return this;
  }

   /**
   * Get renderQueryResult
   * @return renderQueryResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public QueryResult getRenderQueryResult() {
    return renderQueryResult;
  }


  public void setRenderQueryResult(QueryResult renderQueryResult) {
    
    
    
    this.renderQueryResult = renderQueryResult;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RunResult instance itself
   */
  public RunResult putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RunResult runResult = (RunResult) o;
    return Objects.equals(this.isRunning, runResult.isRunning) &&
        Objects.equals(this.name, runResult.name) &&
        Objects.equals(this.nodeID, runResult.nodeID) &&
        Objects.equals(this.queryResults, runResult.queryResults) &&
        Objects.equals(this.renderQueryResult, runResult.renderQueryResult)&&
        Objects.equals(this.additionalProperties, runResult.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isRunning, name, nodeID, queryResults, renderQueryResult, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RunResult {\n");
    sb.append("    isRunning: ").append(toIndentedString(isRunning)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodeID: ").append(toIndentedString(nodeID)).append("\n");
    sb.append("    queryResults: ").append(toIndentedString(queryResults)).append("\n");
    sb.append("    renderQueryResult: ").append(toIndentedString(renderQueryResult)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isRunning");
    openapiFields.add("name");
    openapiFields.add("nodeID");
    openapiFields.add("queryResults");
    openapiFields.add("renderQueryResult");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("isRunning");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("nodeID");
    openapiRequiredFields.add("queryResults");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RunResult
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RunResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RunResult is not found in the empty JSON string", RunResult.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RunResult.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("nodeID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nodeID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nodeID").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("queryResults").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `queryResults` to be an array in the JSON string but got `%s`", jsonObj.get("queryResults").toString()));
      }

      JsonArray jsonArrayqueryResults = jsonObj.getAsJsonArray("queryResults");
      // validate the required field `queryResults` (array)
      for (int i = 0; i < jsonArrayqueryResults.size(); i++) {
        QueryResult.validateJsonObject(jsonArrayqueryResults.get(i).getAsJsonObject());
      };
      // validate the optional field `renderQueryResult`
      if (jsonObj.get("renderQueryResult") != null && !jsonObj.get("renderQueryResult").isJsonNull()) {
        QueryResult.validateJsonObject(jsonObj.getAsJsonObject("renderQueryResult"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RunResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RunResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RunResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RunResult.class));

       return (TypeAdapter<T>) new TypeAdapter<RunResult>() {
           @Override
           public void write(JsonWriter out, RunResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RunResult read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RunResult instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RunResult given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RunResult
  * @throws IOException if the JSON string is invalid with respect to RunResult
  */
  public static RunResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RunResult.class);
  }

 /**
  * Convert an instance of RunResult to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

