/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The field used to sort query results.
 */
@JsonAdapter(RunsOrderBy.Adapter.class)public enum RunsOrderBy {
  
  ID("id"),
  
  RUNSTARTTIME("runStartTime"),
  
  RUNENDTIME("runEndTime");

  private String value;

  RunsOrderBy(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RunsOrderBy fromValue(String value) {
    for (RunsOrderBy b : RunsOrderBy.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RunsOrderBy> {
    @Override
    public void write(final JsonWriter jsonWriter, final RunsOrderBy enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RunsOrderBy read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RunsOrderBy.fromValue(value);
    }
  }
}

