/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ColumnMetadata;
import com.konfigthis.client.model.SourceColumnMetadataJoin;
import com.konfigthis.client.model.SourceMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SourceColumnMetadata
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SourceColumnMetadata {
  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  private List<ColumnMetadata> columns = new ArrayList<>();

  public static final String SERIALIZED_NAME_JOIN = "join";
  @SerializedName(SERIALIZED_NAME_JOIN)
  private SourceColumnMetadataJoin join;

  public static final String SERIALIZED_NAME_SOURCE_MAPPING = "sourceMapping";
  @SerializedName(SERIALIZED_NAME_SOURCE_MAPPING)
  private List<SourceMap> sourceMapping = null;

  public SourceColumnMetadata() {
  }

  public SourceColumnMetadata columns(List<ColumnMetadata> columns) {
    
    
    
    
    this.columns = columns;
    return this;
  }

  public SourceColumnMetadata addColumnsItem(ColumnMetadata columnsItem) {
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<ColumnMetadata> getColumns() {
    return columns;
  }


  public void setColumns(List<ColumnMetadata> columns) {
    
    
    
    this.columns = columns;
  }


  public SourceColumnMetadata join(SourceColumnMetadataJoin join) {
    
    
    
    
    this.join = join;
    return this;
  }

   /**
   * Get join
   * @return join
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SourceColumnMetadataJoin getJoin() {
    return join;
  }


  public void setJoin(SourceColumnMetadataJoin join) {
    
    
    
    this.join = join;
  }


  public SourceColumnMetadata sourceMapping(List<SourceMap> sourceMapping) {
    
    
    
    
    this.sourceMapping = sourceMapping;
    return this;
  }

  public SourceColumnMetadata addSourceMappingItem(SourceMap sourceMappingItem) {
    if (this.sourceMapping == null) {
      this.sourceMapping = new ArrayList<>();
    }
    this.sourceMapping.add(sourceMappingItem);
    return this;
  }

   /**
   * Get sourceMapping
   * @return sourceMapping
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SourceMap> getSourceMapping() {
    return sourceMapping;
  }


  public void setSourceMapping(List<SourceMap> sourceMapping) {
    
    
    
    this.sourceMapping = sourceMapping;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SourceColumnMetadata instance itself
   */
  public SourceColumnMetadata putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceColumnMetadata sourceColumnMetadata = (SourceColumnMetadata) o;
    return Objects.equals(this.columns, sourceColumnMetadata.columns) &&
        Objects.equals(this.join, sourceColumnMetadata.join) &&
        Objects.equals(this.sourceMapping, sourceColumnMetadata.sourceMapping)&&
        Objects.equals(this.additionalProperties, sourceColumnMetadata.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, join, sourceMapping, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceColumnMetadata {\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    join: ").append(toIndentedString(join)).append("\n");
    sb.append("    sourceMapping: ").append(toIndentedString(sourceMapping)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("columns");
    openapiFields.add("join");
    openapiFields.add("sourceMapping");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("columns");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SourceColumnMetadata
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SourceColumnMetadata.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SourceColumnMetadata is not found in the empty JSON string", SourceColumnMetadata.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SourceColumnMetadata.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("columns").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `columns` to be an array in the JSON string but got `%s`", jsonObj.get("columns").toString()));
      }

      JsonArray jsonArraycolumns = jsonObj.getAsJsonArray("columns");
      // validate the required field `columns` (array)
      for (int i = 0; i < jsonArraycolumns.size(); i++) {
        ColumnMetadata.validateJsonObject(jsonArraycolumns.get(i).getAsJsonObject());
      };
      // validate the optional field `join`
      if (jsonObj.get("join") != null && !jsonObj.get("join").isJsonNull()) {
        SourceColumnMetadataJoin.validateJsonObject(jsonObj.getAsJsonObject("join"));
      }
      if (jsonObj.get("sourceMapping") != null && !jsonObj.get("sourceMapping").isJsonNull()) {
        JsonArray jsonArraysourceMapping = jsonObj.getAsJsonArray("sourceMapping");
        if (jsonArraysourceMapping != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sourceMapping").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sourceMapping` to be an array in the JSON string but got `%s`", jsonObj.get("sourceMapping").toString()));
          }

          // validate the optional field `sourceMapping` (array)
          for (int i = 0; i < jsonArraysourceMapping.size(); i++) {
            SourceMap.validateJsonObject(jsonArraysourceMapping.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SourceColumnMetadata.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SourceColumnMetadata' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SourceColumnMetadata> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SourceColumnMetadata.class));

       return (TypeAdapter<T>) new TypeAdapter<SourceColumnMetadata>() {
           @Override
           public void write(JsonWriter out, SourceColumnMetadata value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SourceColumnMetadata read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SourceColumnMetadata instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SourceColumnMetadata given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SourceColumnMetadata
  * @throws IOException if the JSON string is invalid with respect to SourceColumnMetadata
  */
  public static SourceColumnMetadata fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SourceColumnMetadata.class);
  }

 /**
  * Convert an instance of SourceColumnMetadata to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

