/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ColumnMetadata;
import com.konfigthis.client.model.NodeTest;
import com.konfigthis.client.model.SourceMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SQLNodeMetadata
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SQLNodeMetadata {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_APPLIED_NODE_TESTS = "appliedNodeTests";
  @SerializedName(SERIALIZED_NAME_APPLIED_NODE_TESTS)
  private List<NodeTest> appliedNodeTests = new ArrayList<>();

  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  private List<ColumnMetadata> columns = new ArrayList<>();

  public static final String SERIALIZED_NAME_CTE_STRING = "cteString";
  @SerializedName(SERIALIZED_NAME_CTE_STRING)
  private String cteString;

  public static final String SERIALIZED_NAME_DESTINATION_NAME = "destinationName";
  @SerializedName(SERIALIZED_NAME_DESTINATION_NAME)
  private String destinationName;

  public static final String SERIALIZED_NAME_ENABLED_COLUMN_TEST_I_DS = "enabledColumnTestIDs";
  @SerializedName(SERIALIZED_NAME_ENABLED_COLUMN_TEST_I_DS)
  private List<String> enabledColumnTestIDs = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAPPING = "mapping";
  @SerializedName(SERIALIZED_NAME_MAPPING)
  private Map<String, Object> mapping = null;

  public static final String SERIALIZED_NAME_MATERIALIZATION_OPTION = "materializationOption";
  @SerializedName(SERIALIZED_NAME_MATERIALIZATION_OPTION)
  private String materializationOption;

  public static final String SERIALIZED_NAME_SOURCE_MAPPING = "sourceMapping";
  @SerializedName(SERIALIZED_NAME_SOURCE_MAPPING)
  private List<SourceMap> sourceMapping = new ArrayList<>();

  public SQLNodeMetadata() {
  }

  public SQLNodeMetadata description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public SQLNodeMetadata appliedNodeTests(List<NodeTest> appliedNodeTests) {
    
    
    
    
    this.appliedNodeTests = appliedNodeTests;
    return this;
  }

  public SQLNodeMetadata addAppliedNodeTestsItem(NodeTest appliedNodeTestsItem) {
    this.appliedNodeTests.add(appliedNodeTestsItem);
    return this;
  }

   /**
   * Get appliedNodeTests
   * @return appliedNodeTests
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[]", required = true, value = "")

  public List<NodeTest> getAppliedNodeTests() {
    return appliedNodeTests;
  }


  public void setAppliedNodeTests(List<NodeTest> appliedNodeTests) {
    
    
    
    this.appliedNodeTests = appliedNodeTests;
  }


  public SQLNodeMetadata columns(List<ColumnMetadata> columns) {
    
    
    
    
    this.columns = columns;
    return this;
  }

  public SQLNodeMetadata addColumnsItem(ColumnMetadata columnsItem) {
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[]", required = true, value = "")

  public List<ColumnMetadata> getColumns() {
    return columns;
  }


  public void setColumns(List<ColumnMetadata> columns) {
    
    
    
    this.columns = columns;
  }


  public SQLNodeMetadata cteString(String cteString) {
    
    
    
    
    this.cteString = cteString;
    return this;
  }

   /**
   * Get cteString
   * @return cteString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCteString() {
    return cteString;
  }


  public void setCteString(String cteString) {
    
    
    
    this.cteString = cteString;
  }


  public SQLNodeMetadata destinationName(String destinationName) {
    
    
    
    
    this.destinationName = destinationName;
    return this;
  }

   /**
   * Get destinationName
   * @return destinationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDestinationName() {
    return destinationName;
  }


  public void setDestinationName(String destinationName) {
    
    
    
    this.destinationName = destinationName;
  }


  public SQLNodeMetadata enabledColumnTestIDs(List<String> enabledColumnTestIDs) {
    
    
    
    
    this.enabledColumnTestIDs = enabledColumnTestIDs;
    return this;
  }

  public SQLNodeMetadata addEnabledColumnTestIDsItem(String enabledColumnTestIDsItem) {
    this.enabledColumnTestIDs.add(enabledColumnTestIDsItem);
    return this;
  }

   /**
   * Get enabledColumnTestIDs
   * @return enabledColumnTestIDs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getEnabledColumnTestIDs() {
    return enabledColumnTestIDs;
  }


  public void setEnabledColumnTestIDs(List<String> enabledColumnTestIDs) {
    
    
    
    this.enabledColumnTestIDs = enabledColumnTestIDs;
  }


  public SQLNodeMetadata mapping(Map<String, Object> mapping) {
    
    
    
    
    this.mapping = mapping;
    return this;
  }

  public SQLNodeMetadata putMappingItem(String key, Object mappingItem) {
    if (this.mapping == null) {
      this.mapping = new HashMap<>();
    }
    this.mapping.put(key, mappingItem);
    return this;
  }

   /**
   * Get mapping
   * @return mapping
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Object> getMapping() {
    return mapping;
  }


  public void setMapping(Map<String, Object> mapping) {
    
    
    
    this.mapping = mapping;
  }


  public SQLNodeMetadata materializationOption(String materializationOption) {
    
    
    
    
    this.materializationOption = materializationOption;
    return this;
  }

   /**
   * Get materializationOption
   * @return materializationOption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMaterializationOption() {
    return materializationOption;
  }


  public void setMaterializationOption(String materializationOption) {
    
    
    
    this.materializationOption = materializationOption;
  }


  public SQLNodeMetadata sourceMapping(List<SourceMap> sourceMapping) {
    
    
    
    
    this.sourceMapping = sourceMapping;
    return this;
  }

  public SQLNodeMetadata addSourceMappingItem(SourceMap sourceMappingItem) {
    this.sourceMapping.add(sourceMappingItem);
    return this;
  }

   /**
   * Get sourceMapping
   * @return sourceMapping
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<SourceMap> getSourceMapping() {
    return sourceMapping;
  }


  public void setSourceMapping(List<SourceMap> sourceMapping) {
    
    
    
    this.sourceMapping = sourceMapping;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SQLNodeMetadata instance itself
   */
  public SQLNodeMetadata putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SQLNodeMetadata sqLNodeMetadata = (SQLNodeMetadata) o;
    return Objects.equals(this.description, sqLNodeMetadata.description) &&
        Objects.equals(this.appliedNodeTests, sqLNodeMetadata.appliedNodeTests) &&
        Objects.equals(this.columns, sqLNodeMetadata.columns) &&
        Objects.equals(this.cteString, sqLNodeMetadata.cteString) &&
        Objects.equals(this.destinationName, sqLNodeMetadata.destinationName) &&
        Objects.equals(this.enabledColumnTestIDs, sqLNodeMetadata.enabledColumnTestIDs) &&
        Objects.equals(this.mapping, sqLNodeMetadata.mapping) &&
        Objects.equals(this.materializationOption, sqLNodeMetadata.materializationOption) &&
        Objects.equals(this.sourceMapping, sqLNodeMetadata.sourceMapping)&&
        Objects.equals(this.additionalProperties, sqLNodeMetadata.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, appliedNodeTests, columns, cteString, destinationName, enabledColumnTestIDs, mapping, materializationOption, sourceMapping, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SQLNodeMetadata {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    appliedNodeTests: ").append(toIndentedString(appliedNodeTests)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    cteString: ").append(toIndentedString(cteString)).append("\n");
    sb.append("    destinationName: ").append(toIndentedString(destinationName)).append("\n");
    sb.append("    enabledColumnTestIDs: ").append(toIndentedString(enabledColumnTestIDs)).append("\n");
    sb.append("    mapping: ").append(toIndentedString(mapping)).append("\n");
    sb.append("    materializationOption: ").append(toIndentedString(materializationOption)).append("\n");
    sb.append("    sourceMapping: ").append(toIndentedString(sourceMapping)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("appliedNodeTests");
    openapiFields.add("columns");
    openapiFields.add("cteString");
    openapiFields.add("destinationName");
    openapiFields.add("enabledColumnTestIDs");
    openapiFields.add("mapping");
    openapiFields.add("materializationOption");
    openapiFields.add("sourceMapping");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("appliedNodeTests");
    openapiRequiredFields.add("columns");
    openapiRequiredFields.add("enabledColumnTestIDs");
    openapiRequiredFields.add("sourceMapping");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SQLNodeMetadata
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SQLNodeMetadata.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SQLNodeMetadata is not found in the empty JSON string", SQLNodeMetadata.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SQLNodeMetadata.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("appliedNodeTests").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `appliedNodeTests` to be an array in the JSON string but got `%s`", jsonObj.get("appliedNodeTests").toString()));
      }

      JsonArray jsonArrayappliedNodeTests = jsonObj.getAsJsonArray("appliedNodeTests");
      // validate the required field `appliedNodeTests` (array)
      for (int i = 0; i < jsonArrayappliedNodeTests.size(); i++) {
        NodeTest.validateJsonObject(jsonArrayappliedNodeTests.get(i).getAsJsonObject());
      };
      // ensure the json data is an array
      if (!jsonObj.get("columns").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `columns` to be an array in the JSON string but got `%s`", jsonObj.get("columns").toString()));
      }

      JsonArray jsonArraycolumns = jsonObj.getAsJsonArray("columns");
      // validate the required field `columns` (array)
      for (int i = 0; i < jsonArraycolumns.size(); i++) {
        ColumnMetadata.validateJsonObject(jsonArraycolumns.get(i).getAsJsonObject());
      };
      if ((jsonObj.get("cteString") != null && !jsonObj.get("cteString").isJsonNull()) && !jsonObj.get("cteString").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cteString` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cteString").toString()));
      }
      if ((jsonObj.get("destinationName") != null && !jsonObj.get("destinationName").isJsonNull()) && !jsonObj.get("destinationName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationName").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("enabledColumnTestIDs") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("enabledColumnTestIDs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `enabledColumnTestIDs` to be an array in the JSON string but got `%s`", jsonObj.get("enabledColumnTestIDs").toString()));
      }
      if ((jsonObj.get("materializationOption") != null && !jsonObj.get("materializationOption").isJsonNull()) && !jsonObj.get("materializationOption").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `materializationOption` to be a primitive type in the JSON string but got `%s`", jsonObj.get("materializationOption").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("sourceMapping").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `sourceMapping` to be an array in the JSON string but got `%s`", jsonObj.get("sourceMapping").toString()));
      }

      JsonArray jsonArraysourceMapping = jsonObj.getAsJsonArray("sourceMapping");
      // validate the required field `sourceMapping` (array)
      for (int i = 0; i < jsonArraysourceMapping.size(); i++) {
        SourceMap.validateJsonObject(jsonArraysourceMapping.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SQLNodeMetadata.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SQLNodeMetadata' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SQLNodeMetadata> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SQLNodeMetadata.class));

       return (TypeAdapter<T>) new TypeAdapter<SQLNodeMetadata>() {
           @Override
           public void write(JsonWriter out, SQLNodeMetadata value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SQLNodeMetadata read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SQLNodeMetadata instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SQLNodeMetadata given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SQLNodeMetadata
  * @throws IOException if the JSON string is invalid with respect to SQLNodeMetadata
  */
  public static SQLNodeMetadata fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SQLNodeMetadata.class);
  }

 /**
  * Convert an instance of SQLNodeMetadata to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

