/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.NodesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NodesApi
 */
@Disabled
public class NodesApiTest {

    private static NodesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new NodesApi(apiClient);
    }

    /**
     * Get Node
     *
     * Get information about a node in an environment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInformationTest() throws ApiException {
        String environmentID = null;
        String nodeID = null;
        Object response = api.getInformation(environmentID, nodeID)
                .execute();
        // TODO: test validations
    }

    /**
     * List Nodes
     *
     * Get a collection of nodes for an environment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        String environmentID = null;
        Boolean detail = null;
        NodesResponse response = api.list(environmentID)
                .detail(detail)
                .execute();
        // TODO: test validations
    }

}
