/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.RunInfo;
import com.konfigthis.client.model.RunResultsResponse;
import com.konfigthis.client.model.RunStatus;
import com.konfigthis.client.model.RunType;
import com.konfigthis.client.model.RunsOrderBy;
import com.konfigthis.client.model.RunsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RunsApi
 */
@Disabled
public class RunsApiTest {

    private static RunsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new RunsApi(apiClient);
    }

    /**
     * Get Run
     *
     * Gets a single run.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRunDetailsTest() throws ApiException {
        Integer runID = null;
        RunInfo response = api.getRunDetails(runID)
                .execute();
        // TODO: test validations
    }

    /**
     * List Runs
     *
     * Get a collection of information about runs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInformationTest() throws ApiException {
        Integer limit = null;
        Object startingFrom = null;
        RunsOrderBy orderBy = null;
        String orderByDirection = null;
        RunType runType = null;
        RunStatus runStatus = null;
        String environmentID = null;
        Boolean detail = null;
        RunsResponse response = api.listInformation()
                .limit(limit)
                .startingFrom(startingFrom)
                .orderBy(orderBy)
                .orderByDirection(orderByDirection)
                .runType(runType)
                .runStatus(runStatus)
                .environmentID(environmentID)
                .detail(detail)
                .execute();
        // TODO: test validations
    }

    /**
     * List Run Results
     *
     * Get a collection of the results of a deploy or refresh run
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listResultsTest() throws ApiException {
        Integer runID = null;
        RunResultsResponse response = api.listResults(runID)
                .execute();
        // TODO: test validations
    }

}
