/*
 * Coalesce API
 * REST API for performing operations with the Coalesce backend.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.NodesResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class NodesApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public NodesApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public NodesApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getInformationCall(String environmentID, String nodeID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/environments/{environmentID}/nodes/{nodeID}"
            .replace("{" + "environmentID" + "}", localVarApiClient.escapeString(environmentID.toString()))
            .replace("{" + "nodeID" + "}", localVarApiClient.escapeString(nodeID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getInformationValidateBeforeCall(String environmentID, String nodeID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'environmentID' is set
        if (environmentID == null) {
            throw new ApiException("Missing the required parameter 'environmentID' when calling getInformation(Async)");
        }

        // verify the required parameter 'nodeID' is set
        if (nodeID == null) {
            throw new ApiException("Missing the required parameter 'nodeID' when calling getInformation(Async)");
        }

        return getInformationCall(environmentID, nodeID, _callback);

    }


    private ApiResponse<Object> getInformationWithHttpInfo(String environmentID, String nodeID) throws ApiException {
        okhttp3.Call localVarCall = getInformationValidateBeforeCall(environmentID, nodeID, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getInformationAsync(String environmentID, String nodeID, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getInformationValidateBeforeCall(environmentID, nodeID, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetInformationRequestBuilder {
        private final String environmentID;
        private final String nodeID;

        private GetInformationRequestBuilder(String environmentID, String nodeID) {
            this.environmentID = environmentID;
            this.nodeID = nodeID;
        }

        /**
         * Build call for getInformation
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A node for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getInformationCall(environmentID, nodeID, _callback);
        }


        /**
         * Execute getInformation request
         * @return Object
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A node for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public Object execute() throws ApiException {
            ApiResponse<Object> localVarResp = getInformationWithHttpInfo(environmentID, nodeID);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getInformation request with HTTP info returned
         * @return ApiResponse&lt;Object&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A node for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Object> executeWithHttpInfo() throws ApiException {
            return getInformationWithHttpInfo(environmentID, nodeID);
        }

        /**
         * Execute getInformation request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A node for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Object> _callback) throws ApiException {
            return getInformationAsync(environmentID, nodeID, _callback);
        }
    }

    /**
     * Get Node
     * Get information about a node in an environment.
     * @param environmentID The environment ID. (required)
     * @param nodeID The node ID. (required)
     * @return GetInformationRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A node for an environment. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
     </table>
     */
    public GetInformationRequestBuilder getInformation(String environmentID, String nodeID) throws IllegalArgumentException {
        if (environmentID == null) throw new IllegalArgumentException("\"environmentID\" is required but got null");
            

        if (nodeID == null) throw new IllegalArgumentException("\"nodeID\" is required but got null");
            

        return new GetInformationRequestBuilder(environmentID, nodeID);
    }
    private okhttp3.Call listCall(String environmentID, Boolean detail, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/environments/{environmentID}/nodes"
            .replace("{" + "environmentID" + "}", localVarApiClient.escapeString(environmentID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (detail != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("detail", detail));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listValidateBeforeCall(String environmentID, Boolean detail, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'environmentID' is set
        if (environmentID == null) {
            throw new ApiException("Missing the required parameter 'environmentID' when calling list(Async)");
        }

        return listCall(environmentID, detail, _callback);

    }


    private ApiResponse<NodesResponse> listWithHttpInfo(String environmentID, Boolean detail) throws ApiException {
        okhttp3.Call localVarCall = listValidateBeforeCall(environmentID, detail, null);
        Type localVarReturnType = new TypeToken<NodesResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call listAsync(String environmentID, Boolean detail, final ApiCallback<NodesResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listValidateBeforeCall(environmentID, detail, _callback);
        Type localVarReturnType = new TypeToken<NodesResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ListRequestBuilder {
        private final String environmentID;
        private Boolean detail;

        private ListRequestBuilder(String environmentID) {
            this.environmentID = environmentID;
        }

        /**
         * Set detail
         * @param detail Include the full detail of the nodes. (optional, default to false)
         * @return ListRequestBuilder
         */
        public ListRequestBuilder detail(Boolean detail) {
            this.detail = detail;
            return this;
        }
        
        /**
         * Build call for list
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A collection of nodes for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return listCall(environmentID, detail, _callback);
        }


        /**
         * Execute list request
         * @return NodesResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A collection of nodes for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public NodesResponse execute() throws ApiException {
            ApiResponse<NodesResponse> localVarResp = listWithHttpInfo(environmentID, detail);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute list request with HTTP info returned
         * @return ApiResponse&lt;NodesResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A collection of nodes for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<NodesResponse> executeWithHttpInfo() throws ApiException {
            return listWithHttpInfo(environmentID, detail);
        }

        /**
         * Execute list request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A collection of nodes for an environment. </td><td>  -  </td></tr>
            <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<NodesResponse> _callback) throws ApiException {
            return listAsync(environmentID, detail, _callback);
        }
    }

    /**
     * List Nodes
     * Get a collection of nodes for an environment
     * @param environmentID The environment ID. (required)
     * @return ListRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A collection of nodes for an environment. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> User lacks authorization to perform this action. </td><td>  -  </td></tr>
     </table>
     */
    public ListRequestBuilder list(String environmentID) throws IllegalArgumentException {
        if (environmentID == null) throw new IllegalArgumentException("\"environmentID\" is required but got null");
            

        return new ListRequestBuilder(environmentID);
    }
}
